### ISSUE TITLE
Still some references to gemnasium/migrate

### ISSUE THREAD

**Issue by nathany** [db-journey/journey#1]
https://github.com/search?q=org%3Adb-journey+gemnasium&type=Code

**Comment by gravis** [comment]
I have to finish the cleanup asap :)

**Comment by nathany** [comment]
Thanks. I'll test it out when you're ready (specifically the Cassandra driver)

**Comment by gravis** [comment]
Give me until the end of the week to sort everything out :)
Thanks!

**Comment by gravis** [comment]
Actually, I'm starting to think we'd better have ONE executable per driver.
Putting everything in the same exec will probably won't be a good fit on the long run, and that way, we could have specific behaviour if needed.
Also, each time a driver is moving, we'll have to rebuild the main app, I'm not sure it's a good thing.
Any thoughts?

**Comment by nathany** [comment]
Not really sure, but even with a single executable, it should be an improvement. Installing the journey executable may download all sorts of source code, but at least we only need to vendor `migrate` and one driver.

**Comment by gravis** [comment]
I have added executables in the releases tab, and a docker image:  https://hub.docker.com/r/dbjourney/journey/

**Comment by gravis** [comment]
I have removed all references to Gemnasium in the code. 
If you want to help on the cassandra driver, I would be pleased to add you as the driver maintainer.
Thanks
