### ISSUE TITLE
mysql.go:49: undefined: sql.Conn

### ISSUE THREAD

**Issue by bartont** [db-journey/journey#10]
go get results in error:

go get -u github.com/db-journey/journey
 `# github.com/db-journey/mysql-driver
../../../github.com/db-journey/mysql-driver/mysql.go:49: undefined: sql.Conn

**Comment by gravis** [comment]
`go get` is working fine. Are you on `master` in all repos of `db-journey`?

**Comment by bartont** [comment]
sorry. it was a go version problem. go1.9.2 darwin/amd64 has the issue. go1.9.3 darwin/amd64 does not and works fine.
