### ISSUE TITLE
Release artifact for 2.2.3

### ISSUE THREAD

**Issue by pmorelli92** [db-journey/journey#17]
Hello! Is it possible to get artifacts linked to the release for the most common build distros like alpine and ubuntu?

Right now on every service's Dockerfile where I need to use journey; I have to clone the repository and create the binary with `go build` (involving pulling the build-base for dependencies in order to use cgo)

Thanks!

**Comment by gravis** [comment]
Could let me know if https://github.com/db-journey/journey/releases/tag/v2.2.3 works for you?
Thanks

**Comment by pmorelli92** [comment]
Yes, it works perfectly! Thanks!

**Comment by pmorelli92** [comment]
Sorry to reopen @gravis,

I cannot extract this file, in my Dockerfile:

```
RUN wget -c https://github.com/db-journey/journey/releases/download/v2.2.3/journey.linux-amd64.tar.gz && tar -xzf journey.linux-amd64.tar.gz
```

I am getting:

```
gzip: stdin: not in gzip format
tar: Child returned status 1
```

Where with the older version it works.

```
RUN wget -c https://github.com/db-journey/journey/releases/download/v2.1.1/journey.linux-amd64.tar.gz && tar -xzf journey.linux-amd64.tar.gz
```

Also, one thing to notice is that the current tar file is 16MB where the older one is only 3MB.
I think it is corrupted, can you check please?

Thanks a lot for the support! ❤️

**Comment by gravis** [comment]
Sorry for that, I messed up with the files, and uploaded the binary instead of an archive... Could you please re-check now?

**Comment by pmorelli92** [comment]
Hi @gravis, the download is now working perfectly but the bin is not working as expected.

Having the following Dockerfile:

```
FROM alpine:latest
RUN apk update && apk add --no-cache git curl tar

RUN wget -c https://github.com/db-journey/journey/releases/download/v2.2.3/journey.linux-amd64.tar.gz \
    && tar -xzf journey.linux-amd64.tar.gz \
    && mv journey.linux-amd64 alpine-journey \
    && rm -rf journey.linux-amd64.tar.gz

RUN chmod a+x alpine-journey

RUN ls -lha
RUN sh alpine-journey -v

```

I am getting the following error:

```
alpine-journey: line 8: syntax error: unterminated quoted string
```

Am I doing something wrong here?

**Comment by pmorelli92** [comment]
I tried creating my own release with `xgo -go 1.13.4 github.com/db-journey/journey` and copying the linux/amd64 bin but it fails as well :(

**Comment by gravis** [comment]
Yes, you won't be able to use this program with Alpine, it's not a static binary:

```
root@03dc1e3dd997:/go# ldd alpine-journey
        linux-vdso.so.1 (0x00007ffda2d43000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbc77298000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbc77277000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbc770b6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fbc772a3000)
```

This is because https://github.com/mattn/go-sqlite3 is a cgo package, which cannot be compiled without gcc and `CGO_ENABLED=1`. The result is a dynamically linked exec. 
They are two options from there:
- You don't use at all sqlite3, and can remove safely https://github.com/db-journey/journey/blob/master/main.go#L13 before compiling a static binary
- It seems possible to pre-compile `go-sqlite3` and don't rely on gcc once done: https://github.com/mattn/go-sqlite3#installation

Let me know if that helps

**Comment by pmorelli92** [comment]
Hi @gravis, yes I ended up removing the drivers since I am only using it for postgres.

Thank you very much!
