### ISSUE TITLE
Can't execute `journey` on osx via `go get` only by building it by hand

### ISSUE THREAD

**Issue by scottillogical** [db-journey/journey#3]
```
 journey git:(master) ✗ go get github.com/db-journey/journey
 journey git:(master) ✗ journey
[1]    4606 killed     journey
 journey git:(master) ✗ go version
go version go1.8.3 darwin/amd64
 journey git:(master) ✗ ./build/journey.darwin-amd64 # works when I go build
NAME:
   journey.darwin-amd64 - Migrations and cronjobs for databases

USAGE:
   journey.darwin-amd64 [global options] command [command options] [arguments...]

VERSION:
   2.0.0

COMMANDS:
     migrate, m   migrate database
     schedule, s  Schedule cron jobs
     help, h      Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --url value, -u value   Driver URL [$DRIVER_URL]
   --path value, -p value  Files path (default: "./files") [$FILES_PATH]
   --help, -h              show help
   --version, -v           print the version
```

For whatever reason, I can't `go get` and then use the journey executable.  It works for mattes/migrate but not this lib or gemnasium/migrate. I've tried blowing away my go workspace but no dice.

**Comment by scottillogical** [comment]
I did try this is a docker container and it worked fine, so I'm just looking for ideas on whats going wrong here at this point

**Comment by gravis** [comment]
Hi, 
Unfortunately, that's known bug with sqlite3.
Remove the imports for this driver, and you should be ok, while I'm retrieving the reference issue for that.
Thanks

**Comment by gravis** [comment]
Could you make sure your go binaries and libs are all up-to-date?
It seems to be fixed in go 1.8.1: https://github.com/mattn/go-sqlite3/issues/402
Another solution: https://github.com/golang/go/issues/19734

**Comment by scottillogical** [comment]
@gravis I'm using 1.8.3 ```
journey git:(master) ✗ go version
go version go1.8.3 darwin/amd64
```

**Comment by gravis** [comment]
I'll check with my env. in the meantime, do the workarounds work for you?

**Comment by gravis** [comment]
Ok, I have tested on my side, and it seems to work fine:

```
$ go get github.com/db-journey/journey
$ journey
NAME:
   journey - Migrations and cronjobs for databases

USAGE:
   journey [global options] command [command options] [arguments...]

VERSION:
   2.0.0

COMMANDS:
     migrate, m   migrate database
     schedule, s  Schedule cron jobs
     help, h      Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --url value, -u value   Driver URL [$DRIVER_URL]
   --path value, -p value  Files path (default: "./files") [$FILES_PATH]
   --help, -h              show help
   --version, -v           print the version
$ go version
go version go1.8.3 darwin/amd64
```

I suspect some leftover somewhere. Where is `journey` installed when you run `go get` (ie: `which journey`)?
Could you try to wipe out the bin, just in case?

**Comment by gravis** [comment]
Can check with the last version, and go 1.9.3?

**Comment by scottillogical** [comment]
appears to work, thank @gravis
