### ISSUE TITLE
Statically linked binaries for v2.1 please

### ISSUE THREAD

**Issue by nathany** [db-journey/journey#7]
It would be help if journey releases were distributed with binaries that could be downloaded to a server or Docker container for running migrations up or down.

There are tools like https://github.com/goreleaser/goreleaser and https://equinox.io/ to help with that.

One issue is with sqlite support [even though I'm using Postgres]

When I build journey normally and copy it into an Alpine Linux based Docker container, I get this error:

```
./bin/journey 
./bin/journey: No such file or directory
```

Though the file is there:

```
file bin/journey 
bin/journey: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=77826a756dd9730e121e341f3d9cd983c6456a35, not stripped
```

But building with CGO enabled set to zero won't work due to SQLite. 

```
CGO_ENABLED=0 go get -u github.com/db-journey/journey
# github.com/mattn/go-sqlite3
/go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:18: undefined: SQLiteConn
/go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:26: undefined: SQLiteConn
/go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:27: undefined: namedValue
/go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:29: undefined: namedValue
/go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:35: undefined: SQLiteConn
/go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:36: undefined: namedValue
/go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:44: undefined: SQLiteConn
/go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:49: undefined: SQLiteConn
/go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:54: undefined: SQLiteStmt
/go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:63: undefined: SQLiteStmt
/go/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:36: too many errors
...
```

**Comment by gravis** [comment]
Have you tried https://hub.docker.com/r/dbjourney/journey/~/dockerfile/ already?

**Comment by nathany** [comment]
Oh, sorry, I hadn't seen it.

It looks like there are binaries for 2.0 but not 2.1. I will need the fix from #6.

https://github.com/db-journey/journey/releases

**Comment by nathany** [comment]
In the Dockerfile, should
```
curl -OL https://github.com/db-journey/journey/releases/download/v2.0.0/journey-linux-amd64
```
be
```
curl -OL https://github.com/db-journey/journey/releases/download/v2.0.0/journey.linux-amd64.tar.gz
```

I get a Not Found error with the former. Looks like the Dockerfile was written for 1.4.2 before journey was in a gz file.

**Comment by nathany** [comment]
Dockerfile bits for journey

```Docker
FROM golang:1.8.4-alpine

# ...

RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
RUN curl -L https://github.com/db-journey/journey/releases/download/v2.0.0/journey.linux-amd64.tar.gz | tar -xz
RUN mv build/journey.linux-amd64 /bin/journey
```

From docker exec -it mycontainer bash:

```
$ bin/journey -v
Error relocating bin/journey: __vfprintf_chk: symbol not found
Error relocating bin/journey: __fprintf_chk: symbol not found
```

```
$ ldd bin/journey 
	/lib64/ld-linux-x86-64.so.2 (0x7fa86eefa000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fa86eefa000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fa86eefa000)
Error relocating bin/journey: __vfprintf_chk: symbol not found
Error relocating bin/journey: __fprintf_chk: symbol not found

$ apk add --update file
$ file bin/journey 
bin/journey: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, stripped
```

"Static" binary is dynamically linked

**Comment by gravis** [comment]
That's unfortunately because of https://github.com/mattn/go-sqlite3 which a cgo package :(

**Comment by nathany** [comment]
So is there anyway to statically compile it (with sqlite)?

And if not, is there a way to exclude sqlite support in the binary?

**Comment by gravis** [comment]
I've tried a few things, without success so far.
The easiest way for you would be to comment out the inclusion of the sqlite3 driver in https://github.com/db-journey/journey/blob/master/main.go#L13

**Comment by nathany** [comment]
What about installing the sqlite library (.so) in the Docker container?

I'd rather not maintain a fork of journey with sqlite removed.

**Comment by nathany** [comment]
Does this issue help at all? https://github.com/mattn/go-sqlite3/issues/341

**Comment by gravis** [comment]
If you take a look at https://travis-ci.org/db-journey/journey/jobs/313519018, you'll see that the linux binary seems to be ok.
I'll try to remove the darwin and windows ones, and see how it goes with docker hub. If I build journey locally, then the docker image, it's fine.

**Comment by gravis** [comment]
The image is now incredibly larger, but at least it's working (at least for me):

```
$ docker pull dbjourney/journey
Using default tag: latest
latest: Pulling from dbjourney/journey
723254a2c089: Pull complete
5fbe1810bf3b: Pull complete
Digest: sha256:71bc2032a516302d142f7e4fe3cb12262d73dff42dc6b920fe1a22745121f3e8
Status: Downloaded newer image for dbjourney/journey:latest

$ docker run -it --rm dbjourney/journey -h
NAME:
   journey - Migrations and cronjobs for databases

USAGE:
   journey [global options] command [command options] [arguments...]

VERSION:
   2.1.1

COMMANDS:
     migrate, m   migrate database
     schedule, s  Schedule cron jobs
     help, h      Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --url value, -u value   Driver URL [$DRIVER_URL]
   --path value, -p value  Files path (default: "./files") [$FILES_PATH]
   --help, -h              show help
   --version, -v           print the version
```

Can you confirm, so I can close this issue please?

**Comment by nathany** [comment]
Well, I guess that works, but I see you switched to a Debian base image.

So the static binary doesn't work on Alpine, unfortunately. Maybe a Postgres-only binary would be better for that case, since it looks like getting the SQLite driver to run on Alpine is a pain.
